name: Mpesa_Gem

on: 
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
